# Generated by Django 4.1.7 on 2023-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='splender',
            new_name='splenders',
        ),
    ]
