# Generated by Django 4.1.7 on 2023-02-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_rename_splender_splenders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='splenders',
            old_name='fname',
            new_name='memy',
        ),
        migrations.RenameField(
            model_name='splenders',
            old_name='lname',
            new_name='nam',
        ),
        migrations.RenameField(
            model_name='splenders',
            old_name='password',
            new_name='semy',
        ),
    ]
