# Generated by Django 4.1.7 on 2023-02-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0003_rename_fname_splenders_memy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='splenders',
        ),
    ]
